name: WinForms .NET Framework CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore LoginDemo.sln

      - name: Build solution
        run: msbuild LoginDemo.sln /p:Configuration=Release /p:Platform="Any CPU" /m

      - name: Run tests
        run: dotnet test .\LoginDemo.Test\LoginDemo.Test.csproj --configuration Release --no-restore --verbosity normal